name = "SeasonalNaive"
uuid = "4e5a55a7-a1e0-4c7c-8281-8d51e13076a6"
authors = ["Arthur Brigatto <arthur.brigatto@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
